apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
spec:
    replicas: 10
    selector:
      matchLabels:
        app: badbugtracker
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: badbugtracker
      spec:
        containers:
          - image: myapp/latest:latest
            imagePullPolicy: Never
            name: myapp
            ports:
              - containerPort: 8080
