insert into bug (id, title, description, dateofcreation) values
    (1, 'Nondisp fx of 2nd metatarsal bone, r foot, init for opn fx', 'Nondisplaced fracture of second metatarsal bone, right foot, initial encounter for open fracture', '5/10/2021'),
    (2, 'Unsp fracture of right wrist and hand, init for clos fx', 'Unspecified fracture of right wrist and hand, initial encounter for closed fracture', '10/26/2021'),
    (3, 'Traum rupture of ligament of r mid finger at MCP/IP jt, subs', 'Traumatic rupture of other ligament of right middle finger at metacarpophalangeal and interphalangeal joint, subsequent encounter', '4/26/2021'),
    (4, 'Antepartum hemorrhage with afibrinogenemia', 'Antepartum hemorrhage with afibrinogenemia', '3/19/2021'),
    (5, 'Unspecified sprain of other and unspecified finger(s)', 'Unspecified sprain of other and unspecified finger(s)', '11/6/2021'),
    (6, 'Scarlet fever with other complications', 'Scarlet fever with other complications', '7/12/2021'),
    (7, 'Pathological fracture, left ankle, init encntr for fracture', 'Pathological fracture, left ankle, initial encounter for fracture', '2/18/2021'),
    (8, 'Toxic effect of halgn deriv of aromatic hydrocrb, acc, init', 'Toxic effect of other halogen derivatives of aromatic hydrocarbons, accidental (unintentional), initial encounter', '10/1/2021'),
    (9, 'Subluxation of unsp interphalangeal joint of finger, sequela', 'Subluxation of unspecified interphalangeal joint of other finger, sequela', '8/14/2021'),
    (10, 'Suppurative otitis media, unspecified, right ear', 'Suppurative otitis media, unspecified, right ear', '3/9/2021'),
    (11, 'Nondisp fx (avulsion) of medial epicondyle of left humerus', 'Nondisplaced fracture (avulsion) of medial epicondyle of left humerus', '6/3/2021'),
    (12, 'Congenital adrenogenital disorders assoc w enzyme deficiency', 'Congenital adrenogenital disorders associated with enzyme deficiency', '12/20/2020'),
    (13, 'Path fx in neopltc dis, left rad, subs for fx w routn heal', 'Pathological fracture in neoplastic disease, left radius, subsequent encounter for fracture with routine healing', '12/17/2020'),
    (14, 'Centric occlusion maximum intercuspation discrepancy', 'Centric occlusion maximum intercuspation discrepancy', '7/10/2021'),
    (15, 'Laceration with foreign body of left shoulder, subs encntr', 'Laceration with foreign body of left shoulder, subsequent encounter', '5/24/2021'),
    (16, 'Laceration of blood vessels at forarm lv, right arm, init', 'Laceration of other blood vessels at forearm level, right arm, initial encounter', '7/24/2021'),
    (17, 'Subluxation and dislocation of T4/T5-T5/T6 thoracic vertebra', 'Subluxation and dislocation of T4/T5-T5/T6 thoracic vertebra', '4/24/2021'),
    (18, 'Corrosion of first degree of unspecified ear, init encntr', 'Corrosion of first degree of unspecified ear [any part, except ear drum], initial encounter', '5/6/2021'),
    (19, 'Corrosion of first degree of unsp toe(s) (nail), subs encntr', 'Corrosion of first degree of unspecified toe(s) (nail), subsequent encounter', '7/17/2021'),
    (20, 'Burn of third degree of left wrist, sequela', 'Burn of third degree of left wrist, sequela', '11/8/2021'),
    (21, 'Nondisp oblique fx shaft of unsp ulna, 7thD', 'Nondisplaced oblique fracture of shaft of unspecified ulna, subsequent encounter for closed fracture with routine healing', '12/30/2020'),
    (22, 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thJ', 'Nondisplaced supracondylar fracture with intracondylar extension of lower end of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', '6/4/2021'),
    (23, 'Other specified acquired deformities of lower leg', 'Other specified acquired deformities of lower leg', '1/5/2021'),
    (24, 'Slip/trip w/o falling due to stepping on object', 'Slipping, tripping and stumbling without falling due to stepping on object', '11/3/2021'),
    (25, 'Collapsed vert, NEC, lumbosacr rgn, subs for fx w delay heal', 'Collapsed vertebra, not elsewhere classified, lumbosacral region, subsequent encounter for fracture with delayed healing', '8/18/2021'),
    (26, 'Myeloid sarcoma, in relapse', 'Myeloid sarcoma, in relapse', '6/21/2021'),
    (27, 'Car passenger injured in clsn w 2/3-whl mv in traf, subs', 'Car passenger injured in collision with two- or three-wheeled motor vehicle in traffic accident, subsequent encounter', '11/4/2021'),
    (28, 'Milt op involving incendiary bullet, civilian, init', 'Military operations involving incendiary bullet, civilian, initial encounter', '11/24/2021'),
    (29, 'Low-tension glaucoma, bilateral, severe stage', 'Low-tension glaucoma, bilateral, severe stage', '11/17/2021'),
    (30, 'Antivaricose drugs, including sclerosing agents', 'Poisoning by, adverse effect of and underdosing of antivaricose drugs, including sclerosing agents', '5/29/2021'),
    (31, 'Oth comp of fb acc left in body fol unsp procedure, subs', 'Other complications of foreign body accidentally left in body following unspecified procedure, subsequent encounter', '10/22/2021'),
    (32, 'Cannabis abuse with psychotic disorder', 'Cannabis abuse with psychotic disorder', '12/20/2020'),
    (33, 'Displaced comminuted fracture of shaft of ulna, right arm', 'Displaced comminuted fracture of shaft of ulna, right arm', '5/28/2021'),
    (34, 'Sandhoff disease', 'Sandhoff disease', '8/31/2021'),
    (35, 'Dislocation of C3/C4 cervical vertebrae, subs encntr', 'Dislocation of C3/C4 cervical vertebrae, subsequent encounter', '9/27/2021'),
    (36, 'Exudative age-rel mclr degn, bilateral, with inactive scar', 'Exudative age-related macular degeneration, bilateral, with inactive scar', '9/9/2021'),
    (37, 'Toxic effect of mycotoxin food contaminants, assault, subs', 'Toxic effect of other mycotoxin food contaminants, assault, subsequent encounter', '5/20/2021'),
    (38, 'Subluxation and dislocation of ankle joint', 'Subluxation and dislocation of ankle joint', '4/17/2021'),
    (39, 'Corrosion of second degree of left wrist, initial encounter', 'Corrosion of second degree of left wrist, initial encounter', '9/6/2021'),
    (40, 'Complete traumatic amputation of forearm, level unspecified', 'Complete traumatic amputation of forearm, level unspecified', '2/1/2021'),
    (41, 'Secondary osteoarthritis, left hand', 'Secondary osteoarthritis, left hand', '5/11/2021'),
    (42, 'Malar fracture, left side, 7thG', 'Malar fracture, left side, subsequent encounter for fracture with delayed healing', '2/18/2021'),
    (43, 'Pseudopapilledema of optic disc, right eye', 'Pseudopapilledema of optic disc, right eye', '4/12/2021'),
    (44, 'Strain of flexor musc/fasc/tend l rng fngr at forearm level', 'Strain of flexor muscle, fascia and tendon of left ring finger at forearm level', '12/4/2020'),
    (45, 'Lateral disloc of proximal end of tibia, left knee, init', 'Lateral dislocation of proximal end of tibia, left knee, initial encounter', '4/18/2021'),
    (46, 'Osteonecrosis due to drugs, unspecified foot', 'Osteonecrosis due to drugs, unspecified foot', '10/26/2021'),
    (47, 'Machinery accident on board merchant ship', 'Machinery accident on board merchant ship', '10/4/2021'),
    (48, 'Car driver injured in collision w pedal cycle in traf', 'Car driver injured in collision with pedal cycle in traffic accident', '6/14/2021'),
    (49, 'Fracture of fifth metatarsal bone', 'Fracture of fifth metatarsal bone', '2/8/2021'),
    (50, 'Posterior dislocation of right radial head, subs encntr', 'Posterior dislocation of right radial head, subsequent encounter', '5/31/2021');